/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CharteUtilisationRouteImport } from './routes/charte-utilisation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EntrepriseRouteImport } from './routes/entreprise'
import { Route as EntretienBatiRouteImport } from './routes/entretien-bati'
import { Route as FacadesExterieurRouteImport } from './routes/facades-exterieur'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MursRevetementsRouteImport } from './routes/murs-revetements'
import { Route as PeintureDecorationRouteImport } from './routes/peinture-decoration'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as RenovationInterieureRouteImport } from './routes/renovation-interieure'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolsParquetsRouteImport } from './routes/sols-parquets'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAvisRouteImport } from './routes/admin.avis'
import { Route as AdminMediasRouteImport } from './routes/admin.medias'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as RealisationsIndexRouteImport } from './routes/realisations/index'
import { Route as RealisationsSlugRouteImport } from './routes/realisations.$slug'
import { Route as ZonesInterventionIndexRouteImport } from './routes/zones-intervention.index'
import { Route as ZonesInterventionCommuneRouteImport } from './routes/zones-intervention.$commune'
import { Route as AdminConfigurationIndexRouteImport } from './routes/admin.configuration.index'
import { Route as AdminConfigurationCoordonneesRouteImport } from './routes/admin.configuration.coordonnees'
import { Route as AdminConfigurationOutilsRouteImport } from './routes/admin.configuration.outils'
import { Route as AdminConfigurationRedirectionsRouteImport } from './routes/admin.configuration.redirections'
import { Route as AdminPagesIndexRouteImport } from './routes/admin.pages.index'
import { Route as AdminPagesIdRouteImport } from './routes/admin.pages.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CharteUtilisationRoute = CharteUtilisationRouteImport.update({
  id: '/charte-utilisation',
  path: '/charte-utilisation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseRoute = EntrepriseRouteImport.update({
  id: '/entreprise',
  path: '/entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const EntretienBatiRoute = EntretienBatiRouteImport.update({
  id: '/entretien-bati',
  path: '/entretien-bati',
  getParentRoute: () => rootRouteImport,
} as any)
const FacadesExterieurRoute = FacadesExterieurRouteImport.update({
  id: '/facades-exterieur',
  path: '/facades-exterieur',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MursRevetementsRoute = MursRevetementsRouteImport.update({
  id: '/murs-revetements',
  path: '/murs-revetements',
  getParentRoute: () => rootRouteImport,
} as any)
const PeintureDecorationRoute = PeintureDecorationRouteImport.update({
  id: '/peinture-decoration',
  path: '/peinture-decoration',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovationInterieureRoute = RenovationInterieureRouteImport.update({
  id: '/renovation-interieure',
  path: '/renovation-interieure',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolsParquetsRoute = SolsParquetsRouteImport.update({
  id: '/sols-parquets',
  path: '/sols-parquets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvisRoute = AdminAvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediasRoute = AdminMediasRouteImport.update({
  id: '/medias',
  path: '/medias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const RealisationsIndexRoute = RealisationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RealisationsRoute,
} as any)
const RealisationsSlugRoute = RealisationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RealisationsRoute,
} as any)
const ZonesInterventionIndexRoute = ZonesInterventionIndexRouteImport.update({
  id: '/zones-intervention/',
  path: '/zones-intervention/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesInterventionCommuneRoute =
  ZonesInterventionCommuneRouteImport.update({
    id: '/zones-intervention/$commune',
    path: '/zones-intervention/$commune',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminConfigurationIndexRoute = AdminConfigurationIndexRouteImport.update({
  id: '/configuration/',
  path: '/configuration/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigurationCoordonneesRoute =
  AdminConfigurationCoordonneesRouteImport.update({
    id: '/configuration/coordonnees',
    path: '/configuration/coordonnees',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConfigurationOutilsRoute =
  AdminConfigurationOutilsRouteImport.update({
    id: '/configuration/outils',
    path: '/configuration/outils',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConfigurationRedirectionsRoute =
  AdminConfigurationRedirectionsRouteImport.update({
    id: '/configuration/redirections',
    path: '/configuration/redirections',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesIdRoute = AdminPagesIdRouteImport.update({
  id: '/pages/$id',
  path: '/pages/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/charte-utilisation': typeof CharteUtilisationRoute
  '/contact': typeof ContactRoute
  '/entreprise': typeof EntrepriseRoute
  '/entretien-bati': typeof EntretienBatiRoute
  '/facades-exterieur': typeof FacadesExterieurRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/murs-revetements': typeof MursRevetementsRoute
  '/peinture-decoration': typeof PeintureDecorationRoute
  '/realisations': typeof RealisationsRouteWithChildren
  '/renovation-interieure': typeof RenovationInterieureRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sols-parquets': typeof SolsParquetsRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/medias': typeof AdminMediasRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/zones-intervention/$commune': typeof ZonesInterventionCommuneRoute
  '/admin/': typeof AdminIndexRoute
  '/realisations/': typeof RealisationsIndexRoute
  '/zones-intervention/': typeof ZonesInterventionIndexRoute
  '/admin/configuration/coordonnees': typeof AdminConfigurationCoordonneesRoute
  '/admin/configuration/outils': typeof AdminConfigurationOutilsRoute
  '/admin/configuration/redirections': typeof AdminConfigurationRedirectionsRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/configuration/': typeof AdminConfigurationIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/charte-utilisation': typeof CharteUtilisationRoute
  '/contact': typeof ContactRoute
  '/entreprise': typeof EntrepriseRoute
  '/entretien-bati': typeof EntretienBatiRoute
  '/facades-exterieur': typeof FacadesExterieurRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/murs-revetements': typeof MursRevetementsRoute
  '/peinture-decoration': typeof PeintureDecorationRoute
  '/renovation-interieure': typeof RenovationInterieureRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sols-parquets': typeof SolsParquetsRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/medias': typeof AdminMediasRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/zones-intervention/$commune': typeof ZonesInterventionCommuneRoute
  '/admin': typeof AdminIndexRoute
  '/realisations': typeof RealisationsIndexRoute
  '/zones-intervention': typeof ZonesInterventionIndexRoute
  '/admin/configuration/coordonnees': typeof AdminConfigurationCoordonneesRoute
  '/admin/configuration/outils': typeof AdminConfigurationOutilsRoute
  '/admin/configuration/redirections': typeof AdminConfigurationRedirectionsRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/configuration': typeof AdminConfigurationIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/charte-utilisation': typeof CharteUtilisationRoute
  '/contact': typeof ContactRoute
  '/entreprise': typeof EntrepriseRoute
  '/entretien-bati': typeof EntretienBatiRoute
  '/facades-exterieur': typeof FacadesExterieurRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/murs-revetements': typeof MursRevetementsRoute
  '/peinture-decoration': typeof PeintureDecorationRoute
  '/realisations': typeof RealisationsRouteWithChildren
  '/renovation-interieure': typeof RenovationInterieureRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sols-parquets': typeof SolsParquetsRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/medias': typeof AdminMediasRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/zones-intervention/$commune': typeof ZonesInterventionCommuneRoute
  '/admin/': typeof AdminIndexRoute
  '/realisations/': typeof RealisationsIndexRoute
  '/zones-intervention/': typeof ZonesInterventionIndexRoute
  '/admin/configuration/coordonnees': typeof AdminConfigurationCoordonneesRoute
  '/admin/configuration/outils': typeof AdminConfigurationOutilsRoute
  '/admin/configuration/redirections': typeof AdminConfigurationRedirectionsRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/configuration/': typeof AdminConfigurationIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/charte-utilisation'
    | '/contact'
    | '/entreprise'
    | '/entretien-bati'
    | '/facades-exterieur'
    | '/mentions-legales'
    | '/murs-revetements'
    | '/peinture-decoration'
    | '/realisations'
    | '/renovation-interieure'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sols-parquets'
    | '/admin/avis'
    | '/admin/medias'
    | '/admin/messages'
    | '/admin/questions'
    | '/realisations/$slug'
    | '/zones-intervention/$commune'
    | '/admin/'
    | '/realisations/'
    | '/zones-intervention/'
    | '/admin/configuration/coordonnees'
    | '/admin/configuration/outils'
    | '/admin/configuration/redirections'
    | '/admin/pages/$id'
    | '/admin/configuration/'
    | '/admin/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/charte-utilisation'
    | '/contact'
    | '/entreprise'
    | '/entretien-bati'
    | '/facades-exterieur'
    | '/mentions-legales'
    | '/murs-revetements'
    | '/peinture-decoration'
    | '/renovation-interieure'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sols-parquets'
    | '/admin/avis'
    | '/admin/medias'
    | '/admin/messages'
    | '/admin/questions'
    | '/realisations/$slug'
    | '/zones-intervention/$commune'
    | '/admin'
    | '/realisations'
    | '/zones-intervention'
    | '/admin/configuration/coordonnees'
    | '/admin/configuration/outils'
    | '/admin/configuration/redirections'
    | '/admin/pages/$id'
    | '/admin/configuration'
    | '/admin/pages'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/charte-utilisation'
    | '/contact'
    | '/entreprise'
    | '/entretien-bati'
    | '/facades-exterieur'
    | '/mentions-legales'
    | '/murs-revetements'
    | '/peinture-decoration'
    | '/realisations'
    | '/renovation-interieure'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sols-parquets'
    | '/admin/avis'
    | '/admin/medias'
    | '/admin/messages'
    | '/admin/questions'
    | '/realisations/$slug'
    | '/zones-intervention/$commune'
    | '/admin/'
    | '/realisations/'
    | '/zones-intervention/'
    | '/admin/configuration/coordonnees'
    | '/admin/configuration/outils'
    | '/admin/configuration/redirections'
    | '/admin/pages/$id'
    | '/admin/configuration/'
    | '/admin/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  CharteUtilisationRoute: typeof CharteUtilisationRoute
  ContactRoute: typeof ContactRoute
  EntrepriseRoute: typeof EntrepriseRoute
  EntretienBatiRoute: typeof EntretienBatiRoute
  FacadesExterieurRoute: typeof FacadesExterieurRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MursRevetementsRoute: typeof MursRevetementsRoute
  PeintureDecorationRoute: typeof PeintureDecorationRoute
  RealisationsRoute: typeof RealisationsRouteWithChildren
  RenovationInterieureRoute: typeof RenovationInterieureRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolsParquetsRoute: typeof SolsParquetsRoute
  ZonesInterventionCommuneRoute: typeof ZonesInterventionCommuneRoute
  ZonesInterventionIndexRoute: typeof ZonesInterventionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charte-utilisation': {
      id: '/charte-utilisation'
      path: '/charte-utilisation'
      fullPath: '/charte-utilisation'
      preLoaderRoute: typeof CharteUtilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise': {
      id: '/entreprise'
      path: '/entreprise'
      fullPath: '/entreprise'
      preLoaderRoute: typeof EntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entretien-bati': {
      id: '/entretien-bati'
      path: '/entretien-bati'
      fullPath: '/entretien-bati'
      preLoaderRoute: typeof EntretienBatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facades-exterieur': {
      id: '/facades-exterieur'
      path: '/facades-exterieur'
      fullPath: '/facades-exterieur'
      preLoaderRoute: typeof FacadesExterieurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/murs-revetements': {
      id: '/murs-revetements'
      path: '/murs-revetements'
      fullPath: '/murs-revetements'
      preLoaderRoute: typeof MursRevetementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peinture-decoration': {
      id: '/peinture-decoration'
      path: '/peinture-decoration'
      fullPath: '/peinture-decoration'
      preLoaderRoute: typeof PeintureDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovation-interieure': {
      id: '/renovation-interieure'
      path: '/renovation-interieure'
      fullPath: '/renovation-interieure'
      preLoaderRoute: typeof RenovationInterieureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sols-parquets': {
      id: '/sols-parquets'
      path: '/sols-parquets'
      fullPath: '/sols-parquets'
      preLoaderRoute: typeof SolsParquetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avis': {
      id: '/admin/avis'
      path: '/avis'
      fullPath: '/admin/avis'
      preLoaderRoute: typeof AdminAvisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medias': {
      id: '/admin/medias'
      path: '/medias'
      fullPath: '/admin/medias'
      preLoaderRoute: typeof AdminMediasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/realisations/': {
      id: '/realisations/'
      path: '/'
      fullPath: '/realisations/'
      preLoaderRoute: typeof RealisationsIndexRouteImport
      parentRoute: typeof RealisationsRoute
    }
    '/realisations/$slug': {
      id: '/realisations/$slug'
      path: '/$slug'
      fullPath: '/realisations/$slug'
      preLoaderRoute: typeof RealisationsSlugRouteImport
      parentRoute: typeof RealisationsRoute
    }
    '/zones-intervention/': {
      id: '/zones-intervention/'
      path: '/zones-intervention'
      fullPath: '/zones-intervention/'
      preLoaderRoute: typeof ZonesInterventionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones-intervention/$commune': {
      id: '/zones-intervention/$commune'
      path: '/zones-intervention/$commune'
      fullPath: '/zones-intervention/$commune'
      preLoaderRoute: typeof ZonesInterventionCommuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuration/': {
      id: '/admin/configuration/'
      path: '/configuration'
      fullPath: '/admin/configuration/'
      preLoaderRoute: typeof AdminConfigurationIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuration/coordonnees': {
      id: '/admin/configuration/coordonnees'
      path: '/configuration/coordonnees'
      fullPath: '/admin/configuration/coordonnees'
      preLoaderRoute: typeof AdminConfigurationCoordonneesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuration/outils': {
      id: '/admin/configuration/outils'
      path: '/configuration/outils'
      fullPath: '/admin/configuration/outils'
      preLoaderRoute: typeof AdminConfigurationOutilsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuration/redirections': {
      id: '/admin/configuration/redirections'
      path: '/configuration/redirections'
      fullPath: '/admin/configuration/redirections'
      preLoaderRoute: typeof AdminConfigurationRedirectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/$id': {
      id: '/admin/pages/$id'
      path: '/pages/$id'
      fullPath: '/admin/pages/$id'
      preLoaderRoute: typeof AdminPagesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAvisRoute: typeof AdminAvisRoute
  AdminMediasRoute: typeof AdminMediasRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConfigurationCoordonneesRoute: typeof AdminConfigurationCoordonneesRoute
  AdminConfigurationOutilsRoute: typeof AdminConfigurationOutilsRoute
  AdminConfigurationRedirectionsRoute: typeof AdminConfigurationRedirectionsRoute
  AdminPagesIdRoute: typeof AdminPagesIdRoute
  AdminConfigurationIndexRoute: typeof AdminConfigurationIndexRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvisRoute: AdminAvisRoute,
  AdminMediasRoute: AdminMediasRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminConfigurationCoordonneesRoute: AdminConfigurationCoordonneesRoute,
  AdminConfigurationOutilsRoute: AdminConfigurationOutilsRoute,
  AdminConfigurationRedirectionsRoute: AdminConfigurationRedirectionsRoute,
  AdminPagesIdRoute: AdminPagesIdRoute,
  AdminConfigurationIndexRoute: AdminConfigurationIndexRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RealisationsRouteChildren {
  RealisationsSlugRoute: typeof RealisationsSlugRoute
  RealisationsIndexRoute: typeof RealisationsIndexRoute
}

const RealisationsRouteChildren: RealisationsRouteChildren = {
  RealisationsSlugRoute: RealisationsSlugRoute,
  RealisationsIndexRoute: RealisationsIndexRoute,
}

const RealisationsRouteWithChildren = RealisationsRoute._addFileChildren(
  RealisationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  CharteUtilisationRoute: CharteUtilisationRoute,
  ContactRoute: ContactRoute,
  EntrepriseRoute: EntrepriseRoute,
  EntretienBatiRoute: EntretienBatiRoute,
  FacadesExterieurRoute: FacadesExterieurRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MursRevetementsRoute: MursRevetementsRoute,
  PeintureDecorationRoute: PeintureDecorationRoute,
  RealisationsRoute: RealisationsRouteWithChildren,
  RenovationInterieureRoute: RenovationInterieureRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolsParquetsRoute: SolsParquetsRoute,
  ZonesInterventionCommuneRoute: ZonesInterventionCommuneRoute,
  ZonesInterventionIndexRoute: ZonesInterventionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
